hash-format = "sha256"

[[files]]
file = "mods/advanced-loot-info.pw.toml"
hash = "e4665a4ea2f5283d3d95ebd88199687e4dfd5b5002ccce20d3fccd97475c6911"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "e71c04679ff75573cd8ef1003eb167830f794b8979f2bdd3c99d28793f2918b0"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "b4dd3b4217e0cf479207818b743a38f0566faa947e7b7d0b13c91e1a79d35e3c"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "9d0fa5bcf0c786acd008d55bd6573d3a38fbe9261b641ab84f36f02183cdb235"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie.pw.toml"
hash = "80472ed95c490b2e5a828c769f30a1b4ed2b8c502ac2d0f577f1c838aaf7ec5e"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "ddc951666b9b867b0ff7671865a33f15adb5331f3d7c8bc179e0ec86795e020f"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "a7a6a8396dd3842912b9483e6dfd0f39d165700e7eab470d4eab2244fc5d624e"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "b97914d02e3e24091a3fed92803b409ba5a3773668d81292b99e1cd735184996"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "dd18db1413980ef467ac2e86c7e5f3cef26d366119f43121204a442583e7c0bd"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "5f32244bbf7f4864d6570bde7f7223655f52d5df455e7b9fe650b10dee42f830"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "8f534cf725f8fc338c29453a25bbff94c5adba4f4b1815863f5d0f073b8f42e3"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "18f45db393d99493c00150c2d4a74d927fc1eccb575629ef1a1fa72ef950b7ff"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "25c69b6d03bd0cd0ad66a6b44af07dbe748bf008300abbde356b7775259b590f"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "01e094e3599564ea056dc71f42cc10854609a5ffbb3f83415225a3bdcbf8680e"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "e16d6a33648db866dedba7b9f76698025fb5ae4942bb0ea0ed5761135ed0cb99"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "1f9cd4e83ced98ba9f8ccff164ce108990e1e8f8f8205b6c549f7db26f1d8c11"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
hash = "ede11788835bc12a73fa0c1b532139a2dac0ba8e690451b2b887901117f2da4a"
metafile = true

[[files]]
file = "mods/emi-professions-(emip).pw.toml"
hash = "f6f6eb7dc0a8e0ccd1e072cc684cd843f1e79578fa2a603f31b3a8dfe6410b13"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "60e6720aafdfa3304b086f7465917179485a3b2463230505728bd24d54113de3"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "f7bb88ccf59b362d533cef59b28b0cab3ef017ad7462dfbe0daae2a0aa30032e"
metafile = true

[[files]]
file = "mods/enhanced-attack-indicator.pw.toml"
hash = "c4db059d45610ed3022c0167eb3221ab580fad60fe7425c51ea05f71017b00ed"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "53f9648ce088fd8547967a8db379e2b961e200f63da49ead894e676ca19c3851"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "054628ed76bd95bde1dbb4343721f3fbed87c8ad798ce99fc74b1171c39b6400"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "57bddfb35fd9e25cf77d7a318e73c79420f27025e7fcc41adb57e69568b46182"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "76ba469ba67cdf17276da7a629ff85518f4c1dfaaae5ad28d9ee2d6bc79439c5"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "ad4e8689c50fedd770fb5cf28561edbd41f6b483bcfd6e3dd3d0c337789c0110"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "5295b04ce2d1cd0953acb201990dc5a78b3a334f127ab8cadbdcb83d3f4bc301"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "907ed71a8d572d5bc2a8f956b0b0d0fad37e1d5bdd48464041a76ef8fca79cb7"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "c101256f1378c97c9fc082cd2cebb2f90e358fc6602d11e15e65cc5d535d3528"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "6a1fd74a1307161a86e40af4a68ebb5c2b3a04036d688c6a1021f70671f492ef"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "983d9aec075a0c94e1f0f4de901688e8c5aff389be085f21534c3062804d6c70"
metafile = true

[[files]]
file = "mods/jline4mcdsrv.pw.toml"
hash = "e83779f8756fbcc004ec9813a821cf4cd5b1d58f6567d29e830f7a1b31e94fb9"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "1600298f357dfdf6c2c6f457de940d9144505e8afb31a8b9c82f28bb35c2ab05"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "34d75daff8b8260780d97bbc2dc545739399df1d5ac304eeb2f80e23354cf3af"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9236940eafe8e97819f093c3c77236ee47de3b7f97a17f3fcf31114034962611"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "e226757905a685aa4b5a61f3d060d55a01bbd043aabd18d3e8287dd2d8ebfb7b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "46e175b662617498d6f250e57f3f66b1b39a40252933b3466e1ff6a7f6209725"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "f531a8ee70e9d78ee62a84e3fd18088070dcf8f2cee2384a8aabed16dbfafe6c"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "2e26dd4ebd07b97d68a9775b84fae707d8824c926e086bb3bcad11687b3fb204"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "0220080e63da514cdfd5ff73355572eba1ebb0202951e12f95740ce413912fb2"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "537bdd1937193d94cf47f2232e2b38357415e5af8c950d97661b3ae881adbb4e"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "7d5af9f25bc04dd33ec6e55983f7c660d0802461ecad3b5a820dd05dfcef2f70"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
hash = "5ea6f9fdefad7193d99da78fd4aebb62957ff5ae749bc3ea67abbe7272bcac63"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "6e454809d22c0967ace0a59408260da91ce80757d00eaa4720f0496fcd1fddd1"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
hash = "9bceeadea46405d869a5b781efb109ac9fd7b4455c9c536092ccc93a135bad96"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "f013040d2544856ca9f8fe4e07e040aa8a78c87ace3426743a8429d73cba81a3"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/rctapi.pw.toml"
hash = "8ba22e5eece0fd37c9415d193a4e77905ff2d55389a8c3a74548c8a4a6185e4d"
metafile = true

[[files]]
file = "mods/rctmod.pw.toml"
hash = "f3938a56907b2569b548e945e9b2c0e57e055f73e4342f244bbef04160df04c0"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/satin-free-wakes.pw.toml"
hash = "da82584dc5c26adafb4df9b69fa2ed710ead914ce8384058665fcfa85950f5fa"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c8bda7e40ba3e14e7e78d1c1f80be842eb6d0acd21fca7b2e6a962bc810b9e46"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1af09f16a643df0f61f2c799e981aa0b8c109999f0784584a6eff9a81f1c00c1"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "247d0c160732895f6bc4a3cf0f0ccf74f55fc9ea67800e87495b8d817093fbbe"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "461adc31ce2b89cafc5ad2e846b482c68529231ac1d907e39ec62458b22e6b3e"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "6a9b663f2cd6c3f6f35ee30831a8e577aacc27b1851688d2179c9a20b19bde92"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "0a6179657082b15117e18fbc80fd60538dc91024a63006e843cb5dbf1991bcbe"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "8cd4c8bc9d0b3a0059f870c04b0fa273c32812c34e56340d3fa66c5b79cc965e"
metafile = true

[[files]]
file = "mods/swingthrough.pw.toml"
hash = "2f05b23513f7682101e2ab609964833f1b4e8557a3c9b272f7c51d9dfa7ad254"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "86b8e66a5d0bd757376928425aad3413fb4948b8057fdfddedc3697d107bac50"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "19faff688fb5bdd5e0151876da94b1ceb98aedaf411574f494497cef06f7fed9"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "39426bfeeab22ea17f94fd3904dd9b78f9a3c9b4ddcb732b734ddbfd0e3568af"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "8f391603f2b1aaf63717c180e82635b7cd2d57617c02edac60f9d25244731df1"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "58eb7f330c8e2158385fda1a391b1a93faf36459f8d25ccb482e26ce885deb5e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8ffa4ba1466882a5abef6c6d220824f1ce4e228771f854f19e4fceb80598723c"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/better-leaves.pw.toml"
hash = "f23b343e4a4555895e697c5ce98971809056a721e4732e25ea5b6952d91c0180"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
