name = "Epic Cobblemon"
author = "Bwc9876"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2067aab91ee9134f13e4e681ad63669b423f9531e88d784583638fb52d975c91"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
