name = "Gayblemon Neo"
author = "Ellis, Ben, & Cobblemon Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "824c43f09f8a810f49102f5da2d6513fe4fff8d9b27a9468e02ed24af1c34815"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
