name = "Epic Cobblemon"
author = "Bwc9876"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48e91fdd56820bd0244147ff099f8fc85c225f87e59667f970852b0659338631"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
