name = "Epic Cobblemon"
author = "Bwc9876"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84a786f0ba115ec3808d946baf5fdfb6cd2de9c355198fc8a4eb8e35a6f46696"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
