name = "Gayblemon Neo"
author = "Ellis, Ben, & Cobblemon Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe278accea4b0cace238263237c91cbf30d149b86053262b7ab095af848d313c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
