name = "Gayblemon Neo"
author = "Ellis, Ben, & Cobblemon Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfcfefcd8c309b93c398d6abac916e11768b06b336cf2142de84038cd6b3c907"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
