name = "Epic Cobblemon"
author = "Bwc9876"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1831f5e34c321a853016cd18318feb78df00a3807e95300381b48cc552824086"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
