name = "Gayblemon Neo"
author = "Ellis, Ben, & Cobblemon Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6910a58a68d73cffc12697cb7d31e4626d6d954fd935355ca744e513a3909a20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
